### ISSUE TITLE
Problemas con las credenciales de YouTube 

### ISSUE THREAD

**Issue by Abarnatan1** [Malegiraldo22/spotify-to-ytmusic-migrator#1]
Estoy teniendo dificultades para obtener las credenciales de YouTube necesarias para usar el proyecto spotify-to-ytmusic-migrator. He probado con varios navegadores, pero no consigo los valores correctos. Cuando intento filtrar con /browser en la consola, no aparece ningún resultado. También estoy obteniendo un error relacionado con la cookie __Secure-3PAPISID.

**Comment by Malegiraldo22** [comment]
Haz lo siguiente
1. Entra a YouTube Music y abre la consola con F12, asegúrate de estar en la pestaña network
2. Da click en biblioteca o en cualquier link de la pagina
3. Filtra usando /browse, la primera opción que te aparece debe ser. Fíjate que el método de la petición sea POST
![image](https://github.com/user-attachments/assets/236a205c-557b-415e-aa4b-131c9636f044)
4. Ve a request headers y copia todo desde Accept hacia abajo
![image](https://github.com/user-attachments/assets/4706cc62-b57f-4524-93c7-6d141a3e7118)

Con esto debería funcionar y no deberías tener el error de la cookie. Déjame saber si pudiste solucionar el problema

**Comment by Abarnatan1** [comment]
Gracias!! Entrando en biblioteca apareció. 

Ahora la herramienta avanza, me muestra las playlist a copiar, pero cuando selecciono una, me sale error en la conexión con youtube otra vez. 

`Enter the number of the playlist to migrate: 6

Getting songs from 227-452...

Migrating songs to Youtube Music...
Traceback (most recent call last):
  File "/Users/abarnatan/Documents/spotify-to-ytmusic-migrator/./script.py", line 135, in <module>
    main()
    ~~~~^^
  File "/Users/abarnatan/Documents/spotify-to-ytmusic-migrator/./script.py", line 130, in main
    added_tracks, failed_tracks = search_add_ytmusic(ytmusic, tracks, selected_playlist['name'])
                                  ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abarnatan/Documents/spotify-to-ytmusic-migrator/./script.py", line 66, in search_add_ytmusic
    playlist_id = ytmusic.create_playlist(playlist_name, "")
  File "/Users/abarnatan/Documents/spotify-to-ytmusic-migrator/venv/lib/python3.13/site-packages/ytmusicapi/mixins/playlists.py", line 224, in create_playlist
    response = self._send_request(endpoint, body)
  File "/Users/abarnatan/Documents/spotify-to-ytmusic-migrator/venv/lib/python3.13/site-packages/ytmusicapi/ytmusic.py", line 156, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 401: Unauthorized.
You must be signed in to perform this operation.`

**Comment by Malegiraldo22** [comment]
Estas usando otro servicio de youtube al tiempo?
Cuando lo estaba desarrollando me pasó al ver un vídeo en youtube mientras realizaba la transferencia. La recomendación sería no usar nada que tenga que ver con Youtube mientras se realiza la transferencia ya que la cookie cambiaría y se detendría la conexión con el servicio

**Comment by Abarnatan1** [comment]
No, solo tengo abierto https://music.youtube.com/library

**Comment by Malegiraldo22** [comment]
He estado tratando de replicar el error, pero no lo he logrado. Es posible que la cookie haya expirado. Sin embargo, ¿podrías describirme todo el proceso que has estado realizando? Incluyendo qué navegador utilizas. Así podría ofrecerte una mejor solución

**Comment by Abarnatan1** [comment]
Luego de mucho ChatGPT y modificaciones en el script está funcionando!! Gran trabajo, muchas gracias!
